In [2]:
import requests
import pandas as pd
import json
import time

API URL

In [3]:
italki = "https://api.italki.com/api/v2/teachers"

Define the next three functions

In [4]:
def get_data(page, min_price, max_price):
    headers_format = {
        'Accept': 'application/json, text/plain, */*',
        'Accept-Encoding': 'gzip, deflate, br, zstd',
        'Accept-Language': 'en-GB,en-US;q=0.9,en;q=0.8,zh-CN;q=0.7,zh;q=0.6',
        'Content-Length': '130',
        'Content-Type': 'application/json',
        'Origin': 'https://www.italki.com',
        'Priority': 'u=1, i',
        'Referer': 'https://www.italki.com/',
        'Sec-Ch-Ua': '"Chromium";v="148", "Google Chrome";v="148", "Not/A)Brand";v="99"',
        'Sec-Ch-Ua-Platform': '?0',
        'Sec-Ch-Ua-Platform': "Windows",
        'Sec-Fetch-Dest': '',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-site',
        'traceparent': '00-9745674df9a9dfea832a3fdbcf8c0d6a-dac1012c5354968c-01',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
        'x-browser-key': '7659a8a0-5881-4f5c-aa2a-00a970b68205', # Found in the actual POST request
        'x-device': '10',                       # Common default, but check yours
        'x-locale': 'en',
        'x-token': '1782271907gAAAAABqE8Kjr_QrtPsCmUtEUpQMdlkstScwQc2UbuMR72CfyTJ96f-DxnyWRyfc_Ymoc2Vv1z-eTsC9RNcEZYXBeunthmsSWXfIPkItOWxjBZxgYd8h6O4v2W69YYVUIwhN3gtROrpOBUppWC32mN4vRIB8N5dO4d8qikMCAj0lmqcJ_ydqChU='   
    }

    payload = {
        "teach_language": {
            "language": "english",
            "max_price": max_price,
            "min_price": min_price,
        },
        "page": page,
        "page_size": 20,
        "user_timezone": "Asia/Singapore"
    }

    response = requests.post(url = italki, headers = headers_format, json=payload)
    time.sleep(2)
    dictionary = response.json()
    return dictionary

In [4]:
def json_new(page, dictionary):
    file_data = {}
    if str(page) in file_data:
          return False
    else:
        file_data[str(page)] = dictionary
        print(file_data)
        with open("test_1.json", 'w') as file:
                # Load existing data into a dictionary
            json.dump(file_data, file, indent=4)

In [ ]:
def json_existing(first_page, dictionary):
     #CHANGE FILE NAME WHEN NEEDED
    try:
        with open("test_1.json", 'r') as file:
                # Load existing data into a dictionary
                file_data = json.load(file)
        if str(first_page) in file_data:
                print('Error: Duplicating Page')
                return False
        else:
                file_data[str(first_page)] = dictionary
                #CHANGE FILE NAME WHEN NEEDED        
                with open("test_1.json", 'w') as file:
                        # Load existing data into a dictionary
                        json.dump(file_data, file, indent=4)
    except:
        page = 1          
        json_new(page, dictionary)

To check the number of entries of price range

In [5]:
# Change price here
min_price = 700
max_price = min_price + 100
def check_entries(min_price, max_price):
    dictionary = get_data(1, min_price, max_price)
    paging = dictionary['paging']
    return paging

page = check_entries(min_price, max_price)
print(page)
if int(page['total']) % 20 == 0:
    range_until = (int(page['total']) // 20) + 1
else:
    range_until = (int(page['total']) // 20) + 2
print(range_until)

{'page': 1, 'page_size': 20, 'total': 223, 'has_next': 1}
13

Check current json file length

In [7]:
def check_dict_length(dictionary):
    return len(dictionary)

try:
    with open("english_price.json", 'r') as file:
                # Load existing data into a dictionary
                file_data_1 = json.load(file)

    first_page = check_dict_length(file_data_1) + 1
    # first_page = check_dict_length(file_data_1) + 1
    first_page
except:
    print('Unable to read file')

Unable to read file

Check Minimum and Maximum Price

In [6]:
min_price

700

In [7]:
max_price

800

In [8]:
range_until

13

In [9]:
dictionary = get_data(1, min_price, max_price)

In [10]:
dictionary

{'meta': {'performance': 0, 'server_time': 0, 'ver': '2.2.0'},
 'data': [{'is_favor': 0,
   'user_info': {'user_id': 11401921,
    'nickname': 'Teacher Emee',
    'avatar_file_name': '1T114019210',
    'is_tutor': 1,
    'is_pro': 0,
    'origin_country_id': 'PH',
    'is_online': 0,
    'living_country_id': 'PH',
    'origin_city_id': 'PH00000',
    'origin_city_name': 'Other',
    'living_city_id': 'PH00000',
    'living_city_name': 'Other',
    'timezone': 'Asia/Manila',
    'last_login_time': '2026-05-29T03:57:03+00:00'},
   'teacher_info': {'video_url': 'https://www.youtube.com/embed/4mECR4wilCs',
    'video_pic_url': 'https://img.youtube.com/vi/4mECR4wilCs/0.jpg',
    'intro': 'About Me\nHi! I’m Teacher Emee, a licensed professional instructor from the Philippines with 9+ years of ESL experience. With a background in Mass Communication and university teaching, I help beginners, business professionals, and IELTS candidates reach their goals. As a mom who raised fluent English speakers, I truly understand the journey of language learning!\n\nTeaching Style\nI offer a "mistake-friendly," student-centered classroom where you do most of the talking. Whether you need high-level Business English or fun, reward-based lessons for kids, I ensure every session is warm and productive. Let’s turn your goals into confident English, one chat at a time!\n\nI taught students from beginner to advance level. I know that learning a second language is quite challenging but I always give my students the motivation to keep them going. I am a friendly, patient, and understanding teacher. So, I tell my students that it\'s okay to make mistakes because from there you will learn to become better if not the best.\n\nWhen I teach my learners, I make sure their good work will be noticed and give them rewards and praises, especially the young ones. I\'m more of a student-centered kind of teacher which means my students will do most of the talking. I believe that this will help them achieve their goals effectively and reach their full potential. My class has a friendly and warm atmosphere and I make sure that my students learn after every lesson.',
    'short_signature': 'Licensed English Expert | IELTS & Business | 9+ Years Experience',
    'teach_language': [{'language': 'english', 'level': 6}],
    'also_speak': [{'language': 'filipino(tagalog)', 'level': 7},
     {'language': 'japanese', 'level': 4},
     {'language': 'other', 'level': 1}],
    'first_valid_time': '2022-02-25T07:45:33Z',
    'session_count': 7434,
    'pro_rating': '4.9',
    'tutor_rating': '4.9',
    'overall_rating': '4.9',
    'qiniu_video_url': 'https://v.italki.cn/A3456095-322F-4846-A676-379A13E7CCD3.mp4',
    'cover_name': '',
    'instant_lesson_status': 0,
    'qiniu_video_pic_url': 'https://v.italki.cn/4mECR4wilCs.jpg',
    'teacher_material_list': [1, 2, 3, 4, 5, 6, 7, 8],
    'is_new': 0,
    'free_trial': 0,
    'has_trial': 0,
    'instant_now': 0,
    'introduction': '',
    'about_me': 'About Me\nHi! I’m Teacher Emee, a licensed professional instructor from the Philippines with 9+ years of ESL experience. With a background in Mass Communication and university teaching, I help beginners, business professionals, and IELTS candidates reach their goals. As a mom who raised fluent English speakers, I truly understand the journey of language learning!\n\nTeaching Style\nI offer a "mistake-friendly," student-centered classroom where you do most of the talking. Whether you need high-level Business English or fun, reward-based lessons for kids, I ensure every session is warm and productive. Let’s turn your goals into confident English, one chat at a time!\n\nI taught students from beginner to advance level. I know that learning a second language is quite challenging but I always give my students the motivation to keep them going. I am a friendly, patient, and understanding teacher. So, I tell my students that it\'s okay to make mistakes because from there you will learn to become better if not the best.\n\nWhen I teach my learners, I make sure their good work will be noticed and give them rewards and praises, especially the young ones. I\'m more of a student-centered kind of teacher which means my students will do most of the talking. I believe that this will help them achieve their goals effectively and reach their full potential. My class has a friendly and warm atmosphere and I make sure that my students learn after every lesson.',
    'about_teacher': '',
    'teaching_style': None,
    'is_student_full': 0,
    'student_count': 992,
    'teacher_tag': [],
    'teacher_child_tag_id_list': [],
    'cancel_policy': '',
    'interest': '',
    'apply_status': 9,
    'first_complete_time': '2022-02-25T07:45:33+00:00',
    'exp_info': [],
    'edu_info': [{'institution': 'Far Eastern University',
      'major': 'Bachelor of Arts Major in Mass Communication',
      'level': 1,
      'start_year': 1995,
      'end_year': 1999,
      'status': 1,
      'create_time': '2024-03-05T11:37:04Z',
      'edu_id': '7B4190C3-6CEB-4DB3-AB80-1E73DE1EC4B1'}],
    'cert_info': [],
    'specialty_cert': [],
    'sorted_cert_info': [],
    'teaching_experience': [],
    'offline_reason': '',
    'personal_tag': [],
    'teacher_child_tag': [],
    'tools_statistics': [],
    'recording_permission': 1,
    'beginner_friendly_tags': ['TRIO057', 'T0001', 'TRIO058'],
    'available_time': '2026-05-29T08:00:00+00:00'},
   'course_info': {'trial_length': 2,
    'has_trial': 0,
    'trial_price': 500,
    'min_price': 500,
    'trial_session_count': 186,
    'trial_description': "Hi. I will be conducting a trial lesson and see if we're a good fit.  We'll start with an introduction to get to know each other first. Our lesson will be about General English and Conversation Practice. But, I want to know more about your needs and goals as to why you want to study English. Because I believe that in this way I can make a lesson plan to help you achieve your desired results. It is very important to know your level if you're an \n A1, A2, B1, and so on, so the lessons will be according to your English ability. Let me know if you want to use your own materials. But if you have none, I can offer you mine like a pdf file, images, articles, etc. My teaching method is very light and easy to understand. But it is more of a student-centered kind of class.",
    'has_beginner_course': 1},
   'exam_result_shown': {'exam_shown_id': 0,
    'exam_type': 0,
    'level': '',
    'score': 0,
    'show_badge': 0,
    'show_score': 0,
    'url_id': '',
    'user_id': 11401921},
   'pro_course_detail': [{'id': 213939,
     'teacher_id': 11401921,
     'language': 'english',
     'title': 'Basic English for Beginners',
     'description': "The objective for each lesson:\n1. To learn about the alphabet plus names\n2. To learn about numbers \n3.. To learn the articles a, an, and the.\n4. To learn English introductions and farewells\n5. To learn about people, places, and nationalities and the questions who, what, and where\n\nTeaching method:\nI incorporate different kinds of teaching methods in class depending on the needs of the students. These teaching methods are: \na. direct method - I use this when a student makes a mistake which I immediately correct and praises him/her when she/he makes a correct answer.\nb. communicative language teaching - I use this method to enhance the student's ability to speak English by using real-life contexts like making requests, accepting offers, explaining things, and expressing their feelings and preferences.\nc. Total Physical Response - I only use this method when needed especially when a student is struggling in understanding a word or a context.\n\nMaterials:\nI use a variety of materials related to the lesson but there is also an option for the student to use his or her own materials provided it will be sent to me a day before the class so I can prepare for the lesson plan. My materials are not limited to pdf files, PPT, audio, video, images, articles, and so on.",
     'level_lower_limit': 1,
     'level_up_limit': 1,
     'course_category': 'CA001',
     'course_tags': ['T0001', 'T0004', 'T0005'],
     'session_price': 500,
     'student_count': 308,
     'session_count': 3242,
     'create_time': '2022-02-25T05:46:11Z',
     'has_package': 1,
     'price_list': [{'package_price': 2500,
       'session_price': 500,
       'course_id': 213939,
       'package_length': 5,
       'session_length': 2,
       'course_price_id': 805934},
      {'package_price': 2500,
       'session_price': 500,
       'course_id': 213939,
       'package_length': 5,
       'session_length': 3,
       'course_price_id': 805936},
      {'package_price': 2500,
       'session_price': 500,
       'course_id': 213939,
       'package_length': 5,
       'session_length': 4,
       'course_price_id': 805932},
      {'package_price': 5000,
       'session_price': 500,
       'course_id': 213939,
       'package_length': 10,
       'session_length': 4,
       'course_price_id': 805933},
      {'package_price': 7500,
       'session_price': 500,
       'course_id': 213939,
       'package_length': 15,
       'session_length': 4,
       'course_price_id': 782289},
      {'package_price': 10000,
       'session_price': 500,
       'course_id': 213939,
       'package_length': 20,
       'session_length': 4,
       'course_price_id': 782290}]},
    {'id': 229059,
     'teacher_id': 11401921,
     'language': 'english',
     'title': 'Daily English Conversation',
     'description': "This lesson focuses on the student's speaking skills. It's more of a free talk type of class. He/She will practice with me without interruption or any correction. However, at the end of the class, I will point out some room for improvement in terms of pronunciation, intonation, and grammar. I will also inject new vocabulary if needed like synonyms,antonyms, etc.",
     'level_lower_limit': 1,
     'level_up_limit': 4,
     'course_category': 'CA005',
     'course_tags': [],
     'session_price': 600,
     'student_count': 566,
     'session_count': 3677,
     'create_time': '2022-08-29T03:32:46Z',
     'has_package': 1,
     'price_list': [{'package_price': 2750,
       'session_price': 550,
       'course_id': 229059,
       'package_length': 5,
       'session_length': 2,
       'course_price_id': 805941},
      {'package_price': 5500,
       'session_price': 550,
       'course_id': 229059,
       'package_length': 10,
       'session_length': 2,
       'course_price_id': 805942},
      {'package_price': 3000,
       'session_price': 600,
       'course_id': 229059,
       'package_length': 5,
       'session_length': 3,
       'course_price_id': 805943},
      {'package_price': 6000,
       'session_price': 600,
       'course_id': 229059,
       'package_length': 10,
       'session_length': 3,
       'course_price_id': 805944},
      {'package_price': 9000,
       'session_price': 600,
       'course_id': 229059,
       'package_length': 15,
       'session_length': 3,
       'course_price_id': 782417},
      {'package_price': 12000,
       'session_price': 600,
       'course_id': 229059,
       'package_length': 20,
       'session_length': 3,
       'course_price_id': 782422},
      {'package_price': 3000,
       'session_price': 600,
       'course_id': 229059,
       'package_length': 5,
       'session_length': 4,
       'course_price_id': 805939},
      {'package_price': 6000,
       'session_price': 600,
       'course_id': 229059,
       'package_length': 10,
       'session_length': 4,
       'course_price_id': 805940},
      {'package_price': 9000,
       'session_price': 600,
       'course_id': 229059,
       'package_length': 15,
       'session_length': 4,
       'course_price_id': 782418},
      {'package_price': 12000,
       'session_price': 600,
       'course_id': 229059,
       'package_length': 20,
       'session_length': 4,
       'course_price_id': 782419}]},
    {'id': 244127,
     'teacher_id': 11401921,
     'language': 'english',
     'title': 'Interview Preparation',
     'description': 'This lesson will focus on mock interviews for aspiring applicants who are looking for a new job or planning to shift careers.',
     'level_lower_limit': 3,
     'level_up_limit': 4,
     'course_category': 'CA001',
     'course_tags': ['T0001', 'T0002', 'T0005'],
     'session_price': 700,
     'student_count': 60,
     'session_count': 301,
     'create_time': '2024-02-10T06:58:47Z',
     'has_package': 1,
     'price_list': [{'package_price': 2500,
       'session_price': 500,
       'course_id': 244127,
       'package_length': 5,
       'session_length': 2,
       'course_price_id': 806026},
      {'package_price': 5000,
       'session_price': 500,
       'course_id': 244127,
       'package_length': 10,
       'session_length': 2,
       'course_price_id': 806027},
      {'package_price': 7500,
       'session_price': 500,
       'course_id': 244127,
       'package_length': 15,
       'session_length': 2,
       'course_price_id': 782447},
      {'package_price': 10000,
       'session_price': 500,
       'course_id': 244127,
       'package_length': 20,
       'session_length': 2,
       'course_price_id': 782450},
      {'package_price': 3000,
       'session_price': 600,
       'course_id': 244127,
       'package_length': 5,
       'session_length': 3,
       'course_price_id': 806028},
      {'package_price': 6000,
       'session_price': 600,
       'course_id': 244127,
       'package_length': 10,
       'session_length': 3,
       'course_price_id': 806029},
      {'package_price': 9000,
       'session_price': 600,
       'course_id': 244127,
       'package_length': 15,
       'session_length': 3,
       'course_price_id': 782451},
      {'package_price': 12000,
       'session_price': 600,
       'course_id': 244127,
       'package_length': 20,
       'session_length': 3,
       'course_price_id': 782452},
      {'package_price': 3500,
       'session_price': 700,
       'course_id': 244127,
       'package_length': 5,
       'session_length': 4,
       'course_price_id': 806024},
      {'package_price': 7000,
       'session_price': 700,
       'course_id': 244127,
       'package_length': 10,
       'session_length': 4,
       'course_price_id': 806025},
      {'package_price': 10500,
       'session_price': 700,
       'course_id': 244127,
       'package_length': 15,
       'session_length': 4,
       'course_price_id': 782448},
      {'package_price': 14000,
       'session_price': 700,
       'course_id': 244127,
       'package_length': 20,
       'session_length': 4,
       'course_price_id': 782449}]},
    {'id': 285346,
     'teacher_id': 11401921,
     'language': 'english',
     'title': 'IELTS Speaking Part Preparation',
     'description': 'This lesson focuses on IELTS Speaking Part Preparation for students who are planning to take the IELTS.',
     'level_lower_limit': 3,
     'level_up_limit': 5,
     'course_category': 'CA005',
     'course_tags': [],
     'session_price': 700,
     'student_count': 3,
     'session_count': 11,
     'create_time': '2026-03-06T00:06:59Z',
     'has_package': 1,
     'price_list': [{'package_price': 3500,
       'session_price': 700,
       'course_id': 285346,
       'package_length': 5,
       'session_length': 4,
       'course_price_id': 1037207},
      {'package_price': 7000,
       'session_price': 700,
       'course_id': 285346,
       'package_length': 10,
       'session_length': 4,
       'course_price_id': 1037208},
      {'package_price': 10500,
       'session_price': 700,
       'course_id': 285346,
       'package_length': 15,
       'session_length': 4,
       'course_price_id': 1037209},
      {'package_price': 14000,
       'session_price': 700,
       'course_id': 285346,
       'package_length': 20,
       'session_length': 4,
       'course_price_id': 1037210}]},
    {'id': 285347,
     'teacher_id': 11401921,
     'language': 'english',
     'title': 'Business English',
     'description': 'This lesson focuses on business people who are preparing for a business presentation or planning to improve his/her business language skills.',
     'level_lower_limit': 3,
     'level_up_limit': 5,
     'course_category': 'CA005',
     'course_tags': [],
     'session_price': 700,
     'student_count': 7,
     'session_count': 17,
     'create_time': '2026-03-06T00:16:15Z',
     'has_package': 1,
     'price_list': [{'package_price': 3500,
       'session_price': 700,
       'course_id': 285347,
       'package_length': 5,
       'session_length': 4,
       'course_price_id': 1037211},
      {'package_price': 7000,
       'session_price': 700,
       'course_id': 285347,
       'package_length': 10,
       'session_length': 4,
       'course_price_id': 1037212},
      {'package_price': 10500,
       'session_price': 700,
       'course_id': 285347,
       'package_length': 15,
       'session_length': 4,
       'course_price_id': 1037213},
      {'package_price': 14000,
       'session_price': 700,
       'course_id': 285347,
       'package_length': 20,
       'session_length': 4,
       'course_price_id': 1037214}]}],
   'tutor_course_detail': [],
   'teacher_statistics': {'finished_session_list': [{'month': 2,
      'data': 106.0},
     {'month': 3, 'data': 145.0},
     {'month': 4, 'data': 209.0}],
    'response_rate_list': [{'month': 2, 'data': 1.0},
     {'month': 3, 'data': 1.0},
     {'month': 4, 'data': 1.0}],
    'attendance_rate_list': [{'month': 2, 'data': 1.0},
     {'month': 3, 'data': 1.0},
     {'month': 4, 'data': 1.0}],
    'finished_session': 7432,
    'response_rate': 1,
    'attendance_rate': 1,
    'update_time': ''}},
  {'is_favor': 0,
   'user_info': {'user_id': 9921506,
    'nickname': 'Natasha Bhibhi',
    'avatar_file_name': '9T099215060',
    'is_tutor': 1,
    'is_pro': 0,
    'origin_country_id': 'ZA',
    'is_online': 0,
    'living_country_id': 'DE',
    'origin_city_id': 'ZW00001',
    'origin_city_name': 'Harare',
    'living_city_id': 'DE00026',
    'living_city_name': 'Stuttgart',
    'timezone': 'Europe/Berlin',
    'last_login_time': '2026-05-28T19:09:33+00:00'},
   'teacher_info': {'video_url': '',
    'video_pic_url': '',
    'intro': 'Hey there! I’m Natasha, a TEFL-certified English tutor specializing in conversational fluency and exam prep (IELTS/TOEFL). With 3+ years teaching kids, teens, and adults, I love helping students speak confidently—whether for travel, work, or school!\nAs a language learner (German B2, Korean B1, Mandarin A2), I totally get the frustration of tricky grammar or pronunciation. That’s why my lessons blend patience with practical tricks I’ve learned firsthand.\nLet’s make English fun and stress-free—click ‘Book’ and let’s chat! :)',
    'short_signature': 'TEFL-Certified English Teacher | 3+ Years of Experience | Conversational & Practical Learning',
    'teach_language': [{'language': 'english', 'level': 7}],
    'also_speak': [{'language': 'shona', 'level': 7},
     {'language': 'afrikaans', 'level': 6},
     {'language': 'german', 'level': 4},
     {'language': 'korean', 'level': 3},
     {'language': 'chinese', 'level': 2}],
    'first_valid_time': '2021-08-13T16:45:18Z',
    'session_count': 3601,
    'pro_rating': '4.9',
    'tutor_rating': '4.9',
    'overall_rating': '4.9',
    'qiniu_video_url': '',
    'cover_name': '',
    'instant_lesson_status': 0,
    'qiniu_video_pic_url': '',
    'teacher_material_list': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    'is_new': 0,
    'free_trial': 0,
    'has_trial': 0,
    'instant_now': 0,
    'introduction': '',

User Info Table

In [12]:
dictionary['data'][0]['user_info']

{'user_id': 11401921,
 'nickname': 'Teacher Emee',
 'avatar_file_name': '1T114019210',
 'is_tutor': 1,
 'is_pro': 0,
 'origin_country_id': 'PH',
 'is_online': 0,
 'living_country_id': 'PH',
 'origin_city_id': 'PH00000',
 'origin_city_name': 'Other',
 'living_city_id': 'PH00000',
 'living_city_name': 'Other',
 'timezone': 'Asia/Manila',
 'last_login_time': '2026-05-29T03:57:03+00:00'}

In [13]:
teachers = dictionary['data']
teachers[0].keys()

dict_keys(['is_favor', 'user_info', 'teacher_info', 'course_info', 'exam_result_shown', 'pro_course_detail', 'tutor_course_detail', 'teacher_statistics'])

To scale, read the JSON list of dictionaries, append more teachers, put it in a DF then choose the columns needs

In [14]:
user_course_info_list = []
for teacher in teachers:
    user_course_info = teacher['user_info'] | teacher['course_info']
    user_course_info_list.append(user_course_info)

user_course_info
df = pd.DataFrame(user_course_info_list)

In [15]:
df.head()

,user_id,nickname,avatar_file_name,is_tutor,is_pro,origin_country_id,is_online,living_country_id,origin_city_id,origin_city_name,...,living_city_name,timezone,last_login_time,trial_length,has_trial,trial_price,min_price,trial_session_count,trial_description,has_beginner_course
0,11401921,Teacher Emee,1T114019210,1,0,PH,0,PH,PH00000,Other,...,Other,Asia/Manila,2026-05-29T03:57:03+00:00,2,0,500,500,186,Hi. I will be conducting a trial lesson and se...,1
1,9921506,Natasha Bhibhi,9T099215060,1,0,ZA,0,DE,ZW00001,Harare,...,Stuttgart,Europe/Berlin,2026-05-28T19:09:33+00:00,2,0,600,800,464,The lesson will be customized to your needs. T...,1
2,10104741,Coach Divine,3T101047410,1,0,PH,0,PH,PH00121,Calamba,...,Calamba,Asia/Singapore,2026-05-29T04:55:55+00:00,2,0,500,800,113,"Apart from the ""getting to know you"" aspect, t...",0
3,10577802,Camille Ilao,9T105778020,1,0,PH,0,PH,PH00006,Manila,...,Paranaque,Asia/Manila,2026-05-28T23:29:20+00:00,2,0,500,710,0,(Disclaimer: I do not have any qualifications ...,1
4,9494384,Riza Mae TEFL/IELTS,8T094943840,1,0,PH,0,PH,PH00071,Bacolod,...,Bacolod,Asia/Shanghai,2026-05-28T22:17:09+00:00,2,0,500,700,0,Hi dear students! If you want to know about my...,1

In [16]:
user_course_info_df = df[['user_id', 'nickname', 'is_tutor', 'is_pro', 'living_city_name', 'living_city_id', 'trial_length', 'has_trial', 'trial_price', 'min_price', 'trial_session_count']]
user_course_info_df

,user_id,nickname,is_tutor,is_pro,living_city_name,living_city_id,trial_length,has_trial,trial_price,min_price,trial_session_count
0,11401921,Teacher Emee,1,0,Other,PH00000,2,0,500,500,186
1,9921506,Natasha Bhibhi,1,0,Stuttgart,DE00026,2,0,600,800,464
2,10104741,Coach Divine,1,0,Calamba,PH00121,2,0,500,800,113
3,10577802,Camille Ilao,1,0,Paranaque,PH00056,2,0,500,710,0
4,9494384,Riza Mae TEFL/IELTS,1,0,Bacolod,PH00071,2,0,500,700,0
5,8373621,Camille Jewl,1,0,San Pedro,PH00156,2,0,500,800,59
6,8730761,Teacher Rain Pro+,1,0,Manila,PH00006,2,0,500,800,126
7,11137135,Luna Kids/Adults,1,0,Other,PH00000,2,0,800,750,0
8,8281200,Adrian アドせんせい,1,0,Other,JP00000,3,0,690,795,20
9,9979853,Britney,1,0,Quezon City,PH00001,2,0,500,800,128
10,10685078,Richelle,1,0,Bacolod,PH00071,2,0,500,700,0
11,11392731,Chelle,1,0,Batangas,PH00271,2,0,700,800,77
12,12358042,Lavi,1,0,Other,FR00000,2,0,1100,800,0
13,9281806,Mila,1,0,Baguio,PH00141,2,0,500,700,290
14,8008619,Teacher Ria,1,0,Cebu,PH00016,2,0,500,600,61
15,8882739,Faith,1,0,Cebu,PH00016,2,0,500,750,180
16,10854368,Teacher JOEY😍,1,0,General Santos,PH00081,2,0,800,700,253
17,9934037,Anne Rola,1,0,Tacloban,PH00236,2,0,500,500,115
18,9094312,Teacher Julian,1,0,Cavite,PH00376,2,0,600,800,0
19,896917,Faith Valencia,1,0,Olongapo,PH00221,4,0,750,650,388

In [17]:
teachers[0]['teacher_info']['also_speak']

[{'language': 'filipino(tagalog)', 'level': 7},
 {'language': 'japanese', 'level': 4},
 {'language': 'other', 'level': 1}]

Also Speaks Other Languages

_After doing all the languages, clean by creating a master language table and replace all the strings with ints_

In [18]:
also_speak_index_list = []
def check_language(language):
    if language in also_speak_index_list:
        return also_speak_index_list.index(language)
    else:
        also_speak_index_list.append(language)
        return also_speak_index_list.index(language)

In [37]:
also_speak_list = []
for teacher in teachers:
    user_id = teacher['user_info']['user_id']
    for language in teacher['teacher_info']['also_speak']:
        current_language = language['language']
        index = check_language(current_language)
        id_language = {}
        id_language['user_id'] = user_id
        id_language['language'] = index
        # id_language['map'] = index
        also_speak_list.append(id_language)

also_speak_list
df_also_speak_list = pd.DataFrame(also_speak_list)
df_also_speak_list

     user_id  language
0   11401921         0
1   11401921         1
2   11401921         2
3    9921506         3
4    9921506         4
5    9921506         5
6    9921506         6
7    9921506         7
8   10104741         0
9   10104741         2
10  10577802         8
11  10577802         2
12   9494384         2
13   8373621         2
14   8730761         5
15   8730761         9
16   8730761         1
17   8730761         2
18  11137135        10
19  11137135         6
20   8281200         7
21   8281200        11
22   8281200         8
23   9979853         1
24   9979853         6
25   9979853         2
26   9979853         8
27  10685078         2
28  11392731        12
29  12358042        11
30  12358042         6
31  12358042         2
32   9281806         0
33   9281806         2
34   8008619         2
35   8882739         7
36   8882739         1
37   8882739         6
38   8882739         2
39  10854368         8
40  10854368        13
41  10854368         7
42  10854368         9
43  10854368         6
44  10854368        14
45   9934037         0
46   9934037         2

In [44]:
df_languages = pd.DataFrame(also_speak_index_list, columns=['other languages'])
df_languages

           other languages
0        filipino(tagalog)
1                 japanese
2                    other
3                    shona
4                afrikaans
5                   german
6                   korean
7                  chinese
8                  spanish
9                  italian
10      japanese(okinawan)
11                  french
12                 cebuano
13  arabic(modernstandard)
14                    thai

In [45]:
result = pd.merge(df_also_speak_list, df_languages, left_on='language', right_index=True, how="left")
result

     user_id  language         other languages
0   11401921         0       filipino(tagalog)
1   11401921         1                japanese
2   11401921         2                   other
3    9921506         3                   shona
4    9921506         4               afrikaans
5    9921506         5                  german
6    9921506         6                  korean
7    9921506         7                 chinese
8   10104741         0       filipino(tagalog)
9   10104741         2                   other
10  10577802         8                 spanish
11  10577802         2                   other
12   9494384         2                   other
13   8373621         2                   other
14   8730761         5                  german
15   8730761         9                 italian
16   8730761         1                japanese
17   8730761         2                   other
18  11137135        10      japanese(okinawan)
19  11137135         6                  korean
20   8281200         7                 chinese
21   8281200        11                  french
22   8281200         8                 spanish
23   9979853         1                japanese
24   9979853         6                  korean
25   9979853         2                   other
26   9979853         8                 spanish
27  10685078         2                   other
28  11392731        12                 cebuano
29  12358042        11                  french
30  12358042         6                  korean
31  12358042         2                   other
32   9281806         0       filipino(tagalog)
33   9281806         2                   other
34   8008619         2                   other
35   8882739         7                 chinese
36   8882739         1                japanese
37   8882739         6                  korean
38   8882739         2                   other
39  10854368         8                 spanish
40  10854368        13  arabic(modernstandard)
41  10854368         7                 chinese
42  10854368         9                 italian
43  10854368         6                  korean
44  10854368        14                    thai
45   9934037         0       filipino(tagalog)
46   9934037         2                   other

Teacher Statistics

In [56]:
test_stat = {}
test_stat['user_id'] = teachers[0]['user_info']['user_id']
test_stat['finished_session'] = teachers[0]['teacher_statistics']['finished_session']
test_stat['response_rate'] = teachers[0]['teacher_statistics']['response_rate']
test_stat['attendance_rate'] = teachers[0]['teacher_statistics']['attendance_rate']

test_stat

{'user_id': 9921506,
 'finished_session': 3599,
 'response_rate': 1,
 'attendance_rate': 1}

In [58]:
teacher_stats_list = []
for teacher in teachers:
    test_stat = {}
    test_stat['user_id'] = teacher['user_info']['user_id']
    test_stat['finished_session'] = teacher['teacher_statistics']['finished_session']
    test_stat['response_rate'] = teacher['teacher_statistics']['response_rate']
    test_stat['attendance_rate'] = teacher['teacher_statistics']['attendance_rate']
    teacher_stats_list.append(test_stat)

teacher_stats_list
df_teacher_stats = pd.DataFrame(teacher_stats_list)

df_teacher_stats

     user_id  finished_session  response_rate  attendance_rate
0    9921506              3599           1.00             1.00
1   10104741              2136           1.00             0.99
2   10003882              1329           1.00             1.00
3   10577802              1449           0.99             0.99
4    9494384               174           0.95             0.94
5    8373621              1363           1.00             0.99
6    8730761             10112           1.00             1.00
7   11137135               465           1.00             0.95
8    8281200               371           1.00             0.99
9    9979853              2802           1.00             1.00
10  10685078               294           0.96             0.94
11  11392731              4084           1.00             0.99
12  12358042               557           0.97             0.98
13   9281806             10685           1.00             1.00
14   8008619               690           1.00             0.98
15   8882739              2487           1.00             0.99
16  10854368              4219           1.00             1.00
17   9934037              2653           1.00             0.99
18    896917              3785           1.00             0.99
19   2930547              6106           1.00             0.99

Pro Course Detail Table

Build the Pro Course Detail Table and the price list table at the same time

In [78]:
teachers[0]['pro_course_detail'][2]

{'id': 211429,
 'teacher_id': 9921506,
 'language': 'english',
 'title': 'Learn English ( KIDS and TEENS) Beginner to Advanced !',
 'description': "A vibrant and interactive environment where young learners are engaged in fun activities to develop their English language skills. It's filled with colorful visuals, games, songs, and stories tailored to their age and language level. The atmosphere is lively, encouraging participation and fostering a sense of curiosity and confidence in using English. Teachers use a variety of teaching methods, such as role-playing, group discussions, and hands-on activities, to make learning enjoyable and effective. Each lesson is carefully planned to cover essential language areas like vocabulary, grammar, pronunciation, and communication skills, all while keeping the kids entertained and motivated to learn.\n\nWe will use textbooks like :\nEverybody Up\nSuper Minds\nDBE \n\nAnd other materials.",
 'level_lower_limit': 1,
 'level_up_limit': 6,
 'course_category': 'CA001',
 'course_tags': ['T0001', 'T0002', 'T0005'],
 'session_price': 1000,
 'student_count': 57,
 'session_count': 631,
 'create_time': '2022-02-09T10:48:14Z',
 'has_package': 1,
 'price_list': [{'package_price': 3600,
   'session_price': 800,
   'course_id': 211429,
   'package_length': 5,
   'session_length': 2,
   'course_price_id': 838039},
  {'package_price': 4100,
   'session_price': 900,
   'course_id': 211429,
   'package_length': 5,
   'session_length': 3,
   'course_price_id': 846729},
  {'package_price': 4500,
   'session_price': 1000,
   'course_id': 211429,
   'package_length': 5,
   'session_length': 4,
   'course_price_id': 838040}]}

In [ ]:
master_price_list = []
pro_course_detail_list = []
for teacher in teachers:
    for course in teacher['pro_course_detail']:
        for prices in course['price_list']:
            master_price_list.append(prices)
        course_no_price = course.copy()
        del course_no_price['price_list']
        del course_no_price['description']
        del course_no_price['level_lower_limit']
        del course_no_price['level_up_limit']
        del course_no_price['course_category']
        del course_no_price['course_tags']
        del course_no_price['create_time']
        pro_course_detail_list.append(course_no_price)



# df_master_price_list = pd.DataFrame(master_price_list)
# df_master_price_list

# pro_course_detail_list

df_pro_course_detail = pd.DataFrame(pro_course_detail_list)
df_pro_course_detail

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
0,173330,9921506,english,Mastering English Proficiency: IELTS and TOEFL...,800,338,1312,1
1,173342,9921506,english,Vocabulary Mastery and Conversational Fluency,900,406,1187,1
2,211429,9921506,english,Learn English ( KIDS and TEENS) Beginner to Ad...,1000,57,631,1
3,177954,10104741,english,IELTS Preparation - Speaking and Writing,1000,35,135,1
4,182774,10104741,english,CONVERSATIONAL ENGLISH | FREE TALK | Teens an...,900,158,1633,1
...,...,...,...,...,...,...,...,...
119,81739,2930547,filipino(tagalog),One-on-One tutoring: Filipino (Tagalog) or Hil...,700,66,453,1
120,81766,2930547,english,General English / IELTS / Kids / Interview Pre...,700,288,3980,1
121,84959,2930547,english,Math Tutorial,700,36,807,1
122,84980,2930547,english,Informal Tutoring,700,47,694,1
123,233037,2930547,filipino(tagalog),Large Packages,700,4,73,1

In [89]:
master_price_list

[{'package_price': 3000,
  'session_price': 600,
  'course_id': 173330,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 838035},
 {'package_price': 3500,
  'session_price': 700,
  'course_id': 173330,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 846728},
 {'package_price': 4000,
  'session_price': 800,
  'course_id': 173330,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 838036},
 {'package_price': 3600,
  'session_price': 800,
  'course_id': 173342,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 838037},
 {'package_price': 3600,
  'session_price': 800,
  'course_id': 173342,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 846730},
 {'package_price': 4100,
  'session_price': 900,
  'course_id': 173342,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 838038},
 {'package_price': 3600,
  'session_price': 800,
  'course_id': 211429,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 838039},
 {'package_price': 4100,
  'session_price': 900,
  'course_id': 211429,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 846729},
 {'package_price': 4500,
  'session_price': 1000,
  'course_id': 211429,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 838040},
 {'package_price': 2500,
  'session_price': 500,
  'course_id': 177954,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 603001},
 {'package_price': 4500,
  'session_price': 1000,
  'course_id': 177954,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 441517},
 {'package_price': 2700,
  'session_price': 600,
  'course_id': 182774,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 571851},
 {'package_price': 4200,
  'session_price': 900,
  'course_id': 182774,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 455300},
 {'package_price': 4200,
  'session_price': 900,
  'course_id': 187449,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 469146},
 {'package_price': 2500,
  'session_price': 500,
  'course_id': 274314,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 939388},
 {'package_price': 3500,
  'session_price': 800,
  'course_id': 274314,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 939387},
 {'package_price': 2500,
  'session_price': 600,
  'course_id': 176666,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 521602},
 {'package_price': 2900,
  'session_price': 650,
  'course_id': 176666,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 598899},
 {'package_price': 3000,
  'session_price': 700,
  'course_id': 176666,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 437749},
 {'package_price': 2500,
  'session_price': 600,
  'course_id': 176669,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 521603},
 {'package_price': 3000,
  'session_price': 700,
  'course_id': 176669,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 437757},
 {'package_price': 3000,
  'session_price': 600,
  'course_id': 177029,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 497494},
 {'package_price': 3000,
  'session_price': 700,
  'course_id': 177029,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 438751},
 {'package_price': 3000,
  'session_price': 700,
  'course_id': 257691,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 693386},
 {'package_price': 3500,
  'session_price': 800,
  'course_id': 257691,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 693385},
 {'package_price': 3000,
  'session_price': 700,
  'course_id': 257692,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 693388},
 {'package_price': 3500,
  'session_price': 800,
  'course_id': 257692,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 693387},
 {'package_price': 3000,
  'session_price': 600,
  'course_id': 257693,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 693390},
 {'package_price': 3500,
  'session_price': 800,
  'course_id': 257693,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 693389},
 {'package_price': 2600,
  'session_price': 650,
  'course_id': 180997,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 450230},
 {'package_price': 2800,
  'session_price': 700,
  'course_id': 180997,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 450229},
 {'package_price': 3200,
  'session_price': 710,
  'course_id': 180997,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 450228},
 {'package_price': 2800,
  'session_price': 650,
  'course_id': 181463,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 496850},
 {'package_price': 3200,
  'session_price': 750,
  'course_id': 181463,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 480793},
 {'package_price': 3350,
  'session_price': 770,
  'course_id': 181463,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 451589},
 {'package_price': 2500,
  'session_price': 500,
  'course_id': 217656,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 612032},
 {'package_price': 2950,
  'session_price': 700,
  'course_id': 217656,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 612033},
 {'package_price': 3060,
  'session_price': 680,
  'course_id': 217656,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 557726},
 {'package_price': 2800,
  'session_price': 600,
  'course_id': 173669,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 543307},
 {'package_price': 3700,
  'session_price': 800,
  'course_id': 173669,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 543306},
 {'package_price': 3200,
  'session_price': 700,
  'course_id': 173669,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 429041},
 {'package_price': 4500,
  'session_price': 1000,
  'course_id': 173669,
  'package_length': 5,
  'session_length': 6,
  'course_price_id': 448628},
 {'package_price': 3200,
  'session_price': 700,
  'course_id': 173674,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 543310},
 {'package_price': 3600,
  'session_price': 800,
  'course_id': 173674,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 543311},
 {'package_price': 4100,
  'session_price': 900,
  'course_id': 173674,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 429058},
 {'package_price': 5500,
  'session_price': 1200,
  'course_id': 173674,
  'package_length': 5,
  'session_length': 6,
  'course_price_id': 429060},
 {'package_price': 500,
  'session_price': 500,
  'course_id': 173675,
  'package_length': 1,
  'session_length': 2,
  'course_price_id': 470576},
 {'package_price': 6500,
  'session_price': 700,
  'course_id': 173675,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 429061},
 {'package_price': 4500,
  'session_price': 1000,
  'course_id': 173675,
  'package_length': 5,
  'session_length': 6,
  'course_price_id': 429062},
 {'package_price': 3000,
  'session_price': 700,
  'course_id': 179595,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 470577},
 {'package_price': 3500,
  'session_price': 800,
  'course_id': 179595,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 543305},
 {'package_price': 8500,
  'session_price': 900,
  'course_id': 179595,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 446198},
 {'package_price': 5500,
  'session_price': 1200,
  'course_id': 179595,
  'package_length': 5,
  'session_length': 6,
  'course_price_id': 446199},
 {'package_price': 2700,
  'session_price': 600,
  'course_id': 227600,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 887590},
 {'package_price': 4700,
  'session_price': 1000,
  'course_id': 227600,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 589515},
 {'package_price': 4500,
  'session_price': 1000,
  'course_id': 227600,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 589516},
 {'package_price': 9000,
  'session_price': 1000,
  'course_id': 227600,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 887589},
 {'package_price': 800,
  'session_price': 800,
  'course_id': 268758,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 887591},
 {'package_price': 800,
  'session_price': 800,
  'course_id': 268759,
  'package_length': 1,
  'session_length': 4,
  'course_price_id': 887592},
 {'package_price': 2500,
  'session_price': 500,
  'course_id': 184077,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 459064},
 {'package_price': 3000,
  'session_price': 650,
  'course_id': 184077,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 476199},
 {'package_price': 4000,
  'session_price': 800,
  'course_id': 184077,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 459063},
 {'package_price': 2500,
  'session_price': 500,
  'course_id': 184078,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 459066},
 {'package_price': 2700,
  'session_price': 600,
  'course_id': 184078,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 476200},
 {'package_price': 3000,
  'session_price': 700,
  'course_id': 184078,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 459065},
 {'package_price': 2500,
  'session_price': 500,
  'course_id': 185963,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 464475},
 {'package_price': 5000,
  'session_price': 500,
  'course_id': 185963,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 891232},
 {'package_price': 3000,
  'session_price': 700,
  'course_id': 185963,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 476201},
 {'package_price': 3800,
  'session_price': 800,
  'course_id': 185963,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 464474},
 {'package_price': 7500,
  'session_price': 800,
  'course_id': 185963,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 891233},
 {'package_price': 4500,
  'session_price': 1000,
  'course_id': 185963,
  'package_length': 5,
  'session_length': 6,
  'course_price_id': 891231},
 {'package_price': 2500,
  'session_price': 500,
  'course_id': 185965,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 464479},
 {'package_price': 3000,
  'session_price': 650,
  'course_id': 185965,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 476202},
 {'package_price': 4000,
  'session_price': 800,
  'course_id': 185965,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 464478},
 {'package_price': 4700,
  'session_price': 1000,
  'course_id': 185965,
  'package_length': 5,
  'session_length': 6,
  'course_price_id': 638161},
 {'package_price': 6000,
  'session_price': 700,
  'course_id': 185967,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 464483},
 {'package_price': 7000,
  'session_price': 780,
  'course_id': 185967,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 476204},
 {'package_price': 4000,
  'session_price': 850,
  'course_id': 185967,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 464482},
 {'package_price': 2500,
  'session_price': 500,
  'course_id': 186324,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 465445},
 {'package_price': 3000,
  'session_price': 650,
  'course_id': 186324,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 476205},
 {'package_price': 4000,
  'session_price': 800,
  'course_id': 186324,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 465444},
 {'package_price': 3300,
  'session_price': 700,
  'course_id': 278677,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 977174},
 {'package_price': 6500,
  'session_price': 700,
  'course_id': 278677,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 977175},
 {'package_price': 10000,
  'session_price': 700,
  'course_id': 278677,
  'package_length': 15,
  'session_length': 2,
  'course_price_id': 977176},
 {'package_price': 4800,
  'session_price': 1000,
  'course_id': 278677,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 977177},
 {'package_price': 9800,
  'session_price': 1000,
  'course_id': 278677,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 977178},
 {'package_price': 4800,
  'session_price': 1200,
  'course_id': 278677,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 977171},
 {'package_price': 9000,
  'session_price': 1200,
  'course_id': 278677,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 977172},
 {'package_price': 14000,
  'session_price': 1200,
  'course_id': 278677,
  'package_length': 15,
  'session_length': 4,
  'course_price_id': 977173},
 {'package_price': 3300,
  'session_price': 700,
  'course_id': 278678,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 977182},
 {'package_price': 6800,
  'session_price': 700,
  'course_id': 278678,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 977183},
 {'package_price': 10000,
  'session_price': 700,
  'course_id': 278678,
  'package_length': 15,
  'session_length': 2,
  'course_price_id': 977184},
 {'package_price': 3700,
  'session_price': 800,
  'course_id': 278678,
  'package_length': 5,
  'session_length': 3,
  'course_price_id': 977185},
 {'package_price': 7500,
  'session_price': 800,
  'course_id': 278678,
  'package_length': 10,
  'session_length': 3,
  'course_price_id': 977186},
 {'package_price': 11500,
  'session_price': 800,
  'course_id': 278678,
  'package_length': 15,
  'session_length': 3,
  'course_price_id': 977187},
 {'package_price': 4800,
  'session_price': 1000,
  'course_id': 278678,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 977179},
 {'package_price': 9800,
  'session_price': 1000,
  'course_id': 278678,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 977180},
 {'package_price': 14000,
  'session_price': 1000,
  'course_id': 278678,
  'package_length': 15,
  'session_length': 4,
  'course_price_id': 977181},
 {'package_price': 3500,
  'session_price': 700,
  'course_id': 148707,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 602381},
 {'package_price': 7000,
  'session_price': 700,
  'course_id': 148707,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 761152},
 {'package_price': 10000,
  'session_price': 700,
  'course_id': 148707,
  'package_length': 15,
  'session_length': 2,
  'course_price_id': 852218},
 {'package_price': 13000,
  'session_price': 700,
  'course_id': 148707,
  'package_length': 20,
  'session_length': 2,
  'course_price_id': 852219},
 {'package_price': 4000,
  'session_price': 800,
  'course_id': 148707,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 359825},
 {'package_price': 8000,
  'session_price': 800,
  'course_id': 148707,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 887284},
 {'package_price': 11000,
  'session_price': 800,
  'course_id': 148707,
  'package_length': 15,
  'session_length': 4,
  'course_price_id': 887285},
 {'package_price': 14500,
  'session_price': 800,
  'course_id': 148707,
  'package_length': 20,
  'session_length': 4,
  'course_price_id': 887286},
 {'package_price': 3500,
  'session_price': 700,
  'course_id': 148711,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 602382},
 {'package_price': 7000,
  'session_price': 700,
  'course_id': 148711,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 967354},
 {'package_price': 10000,
  'session_price': 700,
  'course_id': 148711,
  'package_length': 15,
  'session_length': 2,
  'course_price_id': 967355},
 {'package_price': 13000,
  'session_price': 700,
  'course_id': 148711,
  'package_length': 20,
  'session_length': 2,
  'course_price_id': 967356},
 {'package_price': 4000,
  'session_price': 800,
  'course_id': 148711,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 359838},
 {'package_price': 8000,
  'session_price': 800,
  'course_id': 148711,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 742432},
 {'package_price': 11000,
  'session_price': 800,
  'course_id': 148711,
  'package_length': 15,
  'session_length': 4,
  'course_price_id': 742433},
 {'package_price': 14500,
  'session_price': 800,
  'course_id': 148711,
  'package_length': 20,
  'session_length': 4,
  'course_price_id': 742434},
 {'package_price': 3500,
  'session_price': 700,
  'course_id': 148799,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 827104},
 {'package_price': 7000,
  'session_price': 700,
  'course_id': 148799,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 827105},
 {'package_price': 10000,
  'session_price': 700,
  'course_id': 148799,
  'package_length': 15,
  'session_length': 2,
  'course_price_id': 967357},
 {'package_price': 13000,
  'session_price': 700,
  'course_id': 148799,
  'package_length': 20,
  'session_length': 2,
  'course_price_id': 967358},
 {'package_price': 4000,
  'session_price': 800,
  'course_id': 148799,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 360052},
 {'package_price': 8000,
  'session_price': 800,
  'course_id': 148799,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 827101},
 {'package_price': 11000,
  'session_price': 800,
  'course_id': 148799,
  'package_length': 15,
  'session_length': 4,
  'course_price_id': 827102},
 {'package_price': 14500,
  'session_price': 800,
  'course_id': 148799,
  'package_length': 20,
  'session_length': 4,
  'course_price_id': 827103},
 {'package_price': 3500,
  'session_price': 700,
  'course_id': 195961,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 665327},
 {'package_price': 7000,
  'session_price': 700,
  'course_id': 195961,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 971060},
 {'package_price': 10000,
  'session_price': 700,
  'course_id': 195961,
  'package_length': 15,
  'session_length': 2,
  'course_price_id': 971061},
 {'package_price': 13000,
  'session_price': 700,
  'course_id': 195961,
  'package_length': 20,
  'session_length': 2,
  'course_price_id': 971062},
 {'package_price': 4000,
  'session_price': 800,
  'course_id': 195961,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 494988},
 {'package_price': 8000,
  'session_price': 800,
  'course_id': 195961,
  'package_length': 10,
  'session_length': 4,
  'course_price_id': 742441},
 {'package_price': 11000,
  'session_price': 800,
  'course_id': 195961,
  'package_length': 15,
  'session_length': 4,
  'course_price_id': 742442},
 {'package_price': 14500,
  'session_price': 800,
  'course_id': 195961,
  'package_length': 20,
  'session_length': 4,
  'course_price_id': 742443},
 {'package_price': 4500,
  'session_price': 900,
  'course_id': 265836,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 925513},
 {'package_price': 5000,
  'session_price': 1000,
  'course_id': 265836,
  'package_length': 5,
  'session_length': 4,
  'course_price_id': 858129},
 {'package_price': 3500,
  'session_price': 700,
  'course_id': 270610,
  'package_length': 5,
  'session_length': 2,
  'course_price_id': 964950},
 {'package_price': 7000,
  'session_price': 700,
  'course_id': 270610,
  'package_length': 10,
  'session_length': 2,
  'course_price_id': 964951},
 {'package_price': 10500,
  'session_price': 700,
  'course_id': 270610,

In [86]:
df_master_price_list = pd.DataFrame(master_price_list)
df_master_price_list

,package_price,session_price,course_id,package_length,session_length,course_price_id
0,3000,600,173330,5,2,838035
1,3500,700,173330,5,3,846728
2,4000,800,173330,5,4,838036
3,3600,800,173342,5,2,838037
4,3600,800,173342,5,3,846730
...,...,...,...,...,...,...
804,2500,500,84959,5,2,176740
805,3300,700,84959,5,4,176739
806,2500,500,84980,5,2,176794
807,3300,700,84980,5,4,176793
808,6600,700,233037,10,4,609655

In [70]:
teachers[1]['pro_course_detail'][1]

{'id': 182774,
 'teacher_id': 10104741,
 'language': 'english',
 'title': 'CONVERSATIONAL ENGLISH  | FREE TALK | Teens and Adults',
 'description': 'Students who wish to utilize and enhance their speaking (and listening) abilities typically enroll in this discussion course.\n\nObjectives\n\nThe goal of this course is to help students improve their English communication abilities by:\n\n- improving fluency through regular speaking activities; \n- expanding vocabulary through discussions, role-plays, presentations on a variety of topics; \n- and developing a solid understanding of oral English communication, as well as basic structures, taught not through explicit conceptual structured teachings, but through communication',
 'level_lower_limit': 1,
 'level_up_limit': 6,
 'course_category': 'CA005',
 'course_tags': [],
 'session_price': 900,
 'student_count': 158,
 'session_count': 1633,
 'create_time': '2021-09-17T20:06:19Z',
 'has_package': 1,
 'price_list': [{'package_price': 2700,
   'session_price': 600,
   'course_id': 182774,
   'package_length': 5,
   'session_length': 2,
   'course_price_id': 571851},
  {'package_price': 4200,
   'session_price': 900,
   'course_id': 182774,
   'package_length': 5,
   'session_length': 4,
   'course_price_id': 455300}]}