In [6]:
import sqlite3
import pandas as pd
import json

In [17]:
with open('../EDA/user_course_info_cleaned.json', 'r') as file:
    user_course_info = json.load(file)

df_user_course_info = pd.DataFrame(user_course_info)

In [8]:
with open('../EDA/teacher_stats_cleaned.json', 'r') as file:
    teacher_stats = json.load(file)

df_teacher_stats = pd.DataFrame(teacher_stats)

In [9]:
with open('../EDA/pro_course_cleaned.json', 'r') as file:
    pro_course = json.load(file)

df_pro_course = pd.DataFrame(pro_course)

In [10]:
with open('../EDA/price_list_cleaned.json', 'r') as file:
    price_list = json.load(file)

df_price_list = pd.DataFrame(price_list)

In [11]:
with open('../EDA/also_speaks_cleaned.json', 'r') as file:
    also_speaks = json.load(file)

df_also_speaks = pd.DataFrame(also_speaks)

In [12]:
with open('../EDA/also_speaks_reference.json', 'r') as file:
    also_speaks_reference = json.load(file)

df_also_speaks_reference = pd.DataFrame(also_speaks_reference)

In [19]:
df_user_course_info

,user_id,nickname,is_tutor,is_pro,origin_country_id,living_country_id,origin_city_id,origin_city_name,living_city_id,living_city_name,timezone,trial_length,has_trial,trial_price,min_price,trial_session_count,has_beginner_course
0,55502,Micky Mick,1,0,CN,CN,CN00226,Fushun,CN00006,Beijing,Asia/Shanghai,2,0,1000,2000,97,1
1,113638,Xin,1,1,CN,CA,,,CA00006,Montreal,America/Toronto,2,0,999,2500,227,0
2,114708,Amy (Féng lǎoshī）,0,1,CN,CN,CN00201,Jilin,CN00201,Jilin,Asia/Shanghai,2,0,500,1990,6,1
3,132815,Julie 줄리,1,0,KR,KR,KR00001,Seoul,KR00001,Seoul,Asia/Seoul,2,0,750,1500,0,1
4,148092,Jhon Jairo,0,1,CO,CO,CO00101,Armenia,CO00006,Medellin,America/Bogota,2,0,1000,2500,182,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10465,32167939,Andrele,1,0,CA,CA,CA00000,Other,CA00000,Other,America/Toronto,2,0,1000,2000,3,1
10466,32168520,Daphne👩🏫🌸💗,1,0,PH,PH,PH00141,Baguio,PH00000,Other,Asia/Manila,3,0,500,700,0,0
10467,32169200,Davide Castellani,1,0,IT,IT,IT00000,Other,IT00000,Other,Europe/Rome,4,0,1400,1400,0,1
10468,32169731,FelixRansford,1,0,GB,ES,GB00281,Exeter,ES00131,Jerez de la Frontera,Europe/Madrid,2,0,600,1400,0,0
10469,32171759,Roselene Noel,1,0,HT,DO,HT00000,Other,DO00000,Other,America/Santo_Domingo,2,0,500,1200,0,0

In [20]:
df_user_course_info.set_index('user_id', inplace=True)

In [21]:
df_user_course_info

,nickname,is_tutor,is_pro,origin_country_id,living_country_id,origin_city_id,origin_city_name,living_city_id,living_city_name,timezone,trial_length,has_trial,trial_price,min_price,trial_session_count,has_beginner_course
user_id,,,,,,,,,,,,,,,,
55502,Micky Mick,1,0,CN,CN,CN00226,Fushun,CN00006,Beijing,Asia/Shanghai,2,0,1000,2000,97,1
113638,Xin,1,1,CN,CA,,,CA00006,Montreal,America/Toronto,2,0,999,2500,227,0
114708,Amy (Féng lǎoshī）,0,1,CN,CN,CN00201,Jilin,CN00201,Jilin,Asia/Shanghai,2,0,500,1990,6,1
132815,Julie 줄리,1,0,KR,KR,KR00001,Seoul,KR00001,Seoul,Asia/Seoul,2,0,750,1500,0,1
148092,Jhon Jairo,0,1,CO,CO,CO00101,Armenia,CO00006,Medellin,America/Bogota,2,0,1000,2500,182,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32167939,Andrele,1,0,CA,CA,CA00000,Other,CA00000,Other,America/Toronto,2,0,1000,2000,3,1
32168520,Daphne👩🏫🌸💗,1,0,PH,PH,PH00141,Baguio,PH00000,Other,Asia/Manila,3,0,500,700,0,0
32169200,Davide Castellani,1,0,IT,IT,IT00000,Other,IT00000,Other,Europe/Rome,4,0,1400,1400,0,1
32169731,FelixRansford,1,0,GB,ES,GB00281,Exeter,ES00131,Jerez de la Frontera,Europe/Madrid,2,0,600,1400,0,0
32171759,Roselene Noel,1,0,HT,DO,HT00000,Other,DO00000,Other,America/Santo_Domingo,2,0,500,1200,0,0

In [ ]:
df_teacher_stats

        user_id  finished_session  response_rate  attendance_rate
0         55502              2689           1.00             1.00
1        113638              8410           1.00             1.00
2        114708                50           0.94             0.98
3        132815              2046           1.00             1.00
4        148092              4109           1.00             1.00
...         ...               ...            ...              ...
10465  32167939                 3           1.00             1.00
10466  32168520                 1           1.00             1.00
10467  32169200                 0           0.00             0.00
10468  32169731                 0           0.00             0.00
10469  32171759                 0           0.00             0.00

[10470 rows x 4 columns]

In [23]:
df_teacher_stats.set_index('user_id', inplace=True)
df_teacher_stats

          finished_session  response_rate  attendance_rate
user_id
55502                 2689           1.00             1.00
113638                8410           1.00             1.00
114708                  50           0.94             0.98
132815                2046           1.00             1.00
148092                4109           1.00             1.00
...                    ...            ...              ...
32167939                 3           1.00             1.00
32168520                 1           1.00             1.00
32169200                 0           0.00             0.00
32169731                 0           0.00             0.00
32171759                 0           0.00             0.00

[10470 rows x 3 columns]

In [24]:
df_pro_course

,id,teacher_id,language,title,session_price,student_count,session_count,has_package
0,375,436016,english,English courses新概念英语（1）,1400,15,106,0
1,555,436016,chinese,Young Learners' Chinese,1600,5,37,1
2,946,502096,serbian,Serbian for all levels! 100% target language l...,2300,80,1113,1
3,3190,436016,chinese,One-on-One Customized Chinese lesson,1500,73,1391,1
4,4042,463477,english,One-on-One tutoring: English,3200,95,1504,1
...,...,...,...,...,...,...,...,...
39030,290784,31481128,french,🗣️ Natural French Conversation: Speak easily !,700,0,0,1
39031,290785,8513543,french,Leçon d'essai,800,0,0,0
39032,290788,29325526,korean,For Long-term Students,1300,0,0,1
39033,290792,6417813,spanish,DELE exam preparation / Preparación para el ex...,2700,0,0,1
39034,290796,31472940,french,French for Kids and Beginners,4000,0,0,1

In [25]:
df_pro_course.set_index('id', inplace=True)
df_pro_course

,teacher_id,language,title,session_price,student_count,session_count,has_package
id,,,,,,,
375,436016,english,English courses新概念英语（1）,1400,15,106,0
555,436016,chinese,Young Learners' Chinese,1600,5,37,1
946,502096,serbian,Serbian for all levels! 100% target language l...,2300,80,1113,1
3190,436016,chinese,One-on-One Customized Chinese lesson,1500,73,1391,1
4042,463477,english,One-on-One tutoring: English,3200,95,1504,1
...,...,...,...,...,...,...,...
290784,31481128,french,🗣️ Natural French Conversation: Speak easily !,700,0,0,1
290785,8513543,french,Leçon d'essai,800,0,0,0
290788,29325526,korean,For Long-term Students,1300,0,0,1
290792,6417813,spanish,DELE exam preparation / Preparación para el ex...,2700,0,0,1
290796,31472940,french,French for Kids and Beginners,4000,0,0,1

In [26]:
df_price_list

,package_price,session_price,course_id,package_length,session_length,course_price_id
0,1100,1100,375,1,3,336
1,10000,1000,555,10,2,494
2,20900,2300,946,10,4,823
3,12000,1300,3190,10,3,3075
4,10000,1000,3190,10,2,3076
...,...,...,...,...,...,...
215822,10200,1100,287665,10,3,1084998
215823,15000,1100,287665,15,3,1084999
215824,20000,1100,287665,20,3,1085000
215825,59999,7498,87801,10,4,1085029
215826,84999,7498,87801,15,4,1085030

In [ ]:
df_price_list.set_index('course_price_id', inplace=True)

KeyError: "None of ['course_price_id'] are in the columns"

In [29]:
df_price_list

,package_price,session_price,course_id,package_length,session_length
course_price_id,,,,,
336,1100,1100,375,1,3
494,10000,1000,555,10,2
823,20900,2300,946,10,4
3075,12000,1300,3190,10,3
3076,10000,1000,3190,10,2
...,...,...,...,...,...
1084998,10200,1100,287665,10,3
1084999,15000,1100,287665,15,3
1085000,20000,1100,287665,20,3
1085029,59999,7498,87801,10,4
1085030,84999,7498,87801,15,4

In [31]:
df_also_speaks_reference

                     0
0              spanish
1               arabic
2     arabic(maghrebi)
3    filipino(tagalog)
4             japanese
..                 ...
205           friulian
206      luxembourgish
207           malagasy
208        greenlandic
209            frisian

[210 rows x 1 columns]

In [32]:
df_also_speaks_reference = df_also_speaks_reference.reset_index()
df_also_speaks_reference = df_also_speaks_reference.rename(columns={0:'language'})

In [34]:
df_also_speaks_reference.set_index('index', inplace=True)
df_also_speaks_reference

                language
index
0                spanish
1                 arabic
2       arabic(maghrebi)
3      filipino(tagalog)
4               japanese
...                  ...
205             friulian
206        luxembourgish
207             malagasy
208          greenlandic
209              frisian

[210 rows x 1 columns]

In [37]:
df_also_speaks.set_index('user_id', inplace=True)
df_also_speaks

          language
user_id
5467830          0
5467830          1
5467830          2
11401921         3
11401921         4
...            ...
23372570         4
23372570         0
8296973        180
8296973         12
8296973         11

[29185 rows x 1 columns]

In [35]:
database_schema = {
    'user_course_info_table': df_user_course_info,
    'teacher_stats_table': df_teacher_stats,
    'pro_course_table': df_pro_course,
    'price_list_table': df_price_list,
    'other_languages_table': df_also_speaks,
    'other_languages_ref_table': df_also_speaks_reference
}

In [38]:
conn = sqlite3.connect('italki_analytics.db')

for table_name, dataframe in database_schema.items():
    
    # Check if the index has an explicit name assigned
    if dataframe.index.name is not None:
        pk_label = dataframe.index.name
    else:
        pk_label = 'id' 
    
    # Write cleanly to SQLite
    dataframe.to_sql(
        name=table_name, 
        con=conn, 
        if_exists='replace', 
        index=True, 
        index_label=pk_label
    )
    print(f"Successfully loaded '{table_name}' using primary key: {pk_label}")

# Always close the connection for DB Browser access
conn.close()

Successfully loaded 'user_course_info_table' using primary key: user_id
Successfully loaded 'teacher_stats_table' using primary key: user_id
Successfully loaded 'pro_course_table' using primary key: id
Successfully loaded 'price_list_table' using primary key: course_price_id
Successfully loaded 'other_languages_table' using primary key: user_id
Successfully loaded 'other_languages_ref_table' using primary key: index